{{- if .Values.job.runInitJob -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cloud-pricing-api.fullname" . }}-init-job
  labels:
    {{- include "cloud-pricing-api.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      labels:
        {{- include "cloud-pricing-api.selectorLabels" . | nindent 12 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ include "cloud-pricing-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 16 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm",  "run", "job:init"]
          resources:
            {{- toYaml .Values.job.resources | nindent 16 }}
          env:
            - name: POSTGRES_HOST
              value: {{ include "cloud-pricing-api.postgresql.host" . }}
            - name: POSTGRES_PORT
              value: {{ include "cloud-pricing-api.postgresql.port" . }}
            - name: POSTGRES_DB
              value: {{ include "cloud-pricing-api.postgresql.database" . }}
            - name: POSTGRES_USER
              value: {{ include "cloud-pricing-api.postgresql.user" . }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloud-pricing-api.postgresql.secretName" . }}
                  key: postgresql-password
            - name: INFRACOST_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloud-pricing-api.fullname" . }}
                  key: infracost-api-key
            {{- if not .Values.api.disableSelfHostedInfracostAPIKey }}
            - name: SELF_HOSTED_INFRACOST_PRICING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloud-pricing-api.fullname" . }}
                  key: self-hosted-infracost-api-key
            {{- end }}
            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
      {{- with .Values.job.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.job.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.job.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
{{- end -}}
