{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "cloud-pricing-api.fullname" . }}-cronjob
  labels:
    {{- include "cloud-pricing-api.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.job.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ .Values.job.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.job.backoffLimit }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          serviceAccountName: {{ include "cloud-pricing-api.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            {{- with .Values.job.extraContainers }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["npm", "run", "job:update"]
              resources:
                {{- toYaml .Values.job.resources | nindent 16 }}
              env:
                - name: POSTGRES_HOST
                  value: {{ include "cloud-pricing-api.postgresql.host" . }}
                - name: POSTGRES_PORT
                  value: {{ include "cloud-pricing-api.postgresql.port" . }}
                - name: POSTGRES_DB
                  value: {{ include "cloud-pricing-api.postgresql.database" . }}
                - name: POSTGRES_USER
                  value: {{ include "cloud-pricing-api.postgresql.user" . }}
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "cloud-pricing-api.postgresql.secretName" . }}
                      key: postgresql-password
                - name: INFRACOST_API_KEY
                  valueFrom:
                    secretKeyRef:
                      {{- if not .Values.existingSecretAPIKey }}
                      name: {{ include "cloud-pricing-api.fullname" . }}
                      {{- else }}
                      name: {{ .Values.apiKey.existingSecret }}
                      {{- end }}
                      key: infracost-api-key
                {{- if .Values.job.infracostPricingAPIEndpoint }}
                - name: INFRACOST_PRICING_API_ENDPOINT
                  value: {{ .Values.job.infracostPricingAPIEndpoint }}
                {{- end}}
                {{- if not .Values.api.disableSelfHostedInfracostAPIKey }}
                - name: SELF_HOSTED_INFRACOST_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "cloud-pricing-api.fullname" . }}
                      key: self-hosted-infracost-api-key
                {{- end }}
                - name: LOG_LEVEL
                  value: {{ .Values.job.logLevel | quote }}
                {{- if .Values.extraEnv }}
                {{- toYaml .Values.extraEnv | nindent 16 }}
                {{- end }}
          {{- with .Values.job.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.job.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.job.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
